### PR TITLE
Repo urls special chars fixes #120

### LINKED ISSUE #120: Support special chars, e.g. "~" in repo urls
Some repository urls contain a "~". Kontrolletti responds with `400 Bad Request` when trying to normalize such repository urls.

## Expected behavior

Special characters should be supported in repository urls (as long as they are [valid URI chars](http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid/1547940#1547940))

### PR DESCRIPTION
**Pull request by lotharschulz**

### CODE REVIEW

**Comment by lotharschulz** [comment]
@kanuku : opened this pr as early as possible following one idea of https://guides.github.com/introduction/flow/

**Comment by lotharschulz** [comment]
* https://travis-ci.org/zalando/kontrolletti/builds/93141708 is green now, had a hickup downloading one artefact
* start additional smoke tests tomorrow

**Comment by lotharschulz** [comment]
@kanuku : smoke test done, pls comment :thumbsup: to merge this one or :thumbsdown: if not ready for merge

**Comment by kanuku** [comment]
(y)

**Pull request merged**
